[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = sOYkLn0yQ0bcyilUP/54dtdUZwHBHdEB9LX76pJj9XM=
Address = 10.2.0.2/32
DNS = 10.2.0.1
Table = off
PostUp = ip route add 149.88.17.182/32 via 192.168.1.1 dev wlan0; ip route del default via 192.168.1.1 dev wlan0; ip route add default dev %i
PreDown = ip route del default dev %i; ip route add default via 192.168.1.1 dev wlan0; ip route del 149.88.17.182/32 via 192.168.1.1 dev wlan0

[Peer]
# MX-FREE#7
PublicKey = G1H7jHJjOxnNXy0GPQNRT5ikSESyagGePfG1COP+4Hs=
AllowedIPs = 0.0.0.0/0
Endpoint = 149.88.17.182:51820

PersistentKeepalive = 25
